In [1]:
import os
import pandas as pd
import numpy as np
from MarkowitzPortfolioOptimizer import *

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
def get_file_paths(directory):
    """
    Récupère tous les chemins des fichiers dans un dossier donné.

    Args:
        directory (str): Le chemin du dossier.

    Returns:
        list: Une liste contenant les chemins complets des fichiers dans le dossier.
    """
    file_paths = []
    for root, _, files in os.walk(directory):
        for file in files:
            file_paths.append(os.path.join(root, file))
    return file_paths

In [3]:
list=get_file_paths("test_prices")

In [4]:
list

['test_prices/basep-10_Holofoil.csv',
 'test_prices/hgss1-13_Holofoil.csv',
 'test_prices/ex3-1_Holofoil.csv',
 'test_prices/ex5-7_Holofoil.csv',
 'test_prices/bw5-2_Reverse_Holofoil.csv',
 'test_prices/ex7-4_Reverse_Holofoil.csv',
 'test_prices/smp-SM04_Holofoil.csv',
 'test_prices/col1-3_Holofoil.csv',
 'test_prices/pop7-4_Normal.csv',
 'test_prices/base4-12_Holofoil.csv',
 'test_prices/ex4-1_Holofoil.csv',
 'test_prices/base6-2_Reverse_Holofoil.csv',
 'test_prices/col1-2_Holofoil.csv',
 'test_prices/xy3-5_Holofoil.csv',
 'test_prices/base1-11_Holofoil.csv',
 'test_prices/g1-2_Holofoil.csv',
 'test_prices/base1-13_Holofoil.csv',
 'test_prices/dp1-2_Holofoil.csv',
 'test_prices/basep-9_Holofoil.csv',
 'test_prices/base4-11_Holofoil.csv',
 'test_prices/base1-12_Holofoil.csv',
 'test_prices/sm9-14_Reverse_Holofoil.csv',
 'test_prices/base4-9_Holofoil.csv',
 'test_prices/bw11-3_Reverse_Holofoil.csv',
 'test_prices/pl1-5_Holofoil.csv',
 'test_prices/pl1-3_Holofoil.csv',
 'test_prices/xy2-

In [5]:

def get_file_paths(directory):
    """
    Récupère tous les chemins des fichiers dans un dossier donné.

    Args:
        directory (str): Le chemin du dossier.

    Returns:
        list: Une liste contenant les chemins complets des fichiers dans le dossier.
    """
    file_paths = []
    for root, _, files in os.walk(directory):
        for file in files:
            file_paths.append(os.path.join(root, file))
    return file_paths


In [6]:
path=get_file_paths("test_prices")

In [7]:
path

['test_prices/basep-10_Holofoil.csv',
 'test_prices/hgss1-13_Holofoil.csv',
 'test_prices/ex3-1_Holofoil.csv',
 'test_prices/ex5-7_Holofoil.csv',
 'test_prices/bw5-2_Reverse_Holofoil.csv',
 'test_prices/ex7-4_Reverse_Holofoil.csv',
 'test_prices/smp-SM04_Holofoil.csv',
 'test_prices/col1-3_Holofoil.csv',
 'test_prices/pop7-4_Normal.csv',
 'test_prices/base4-12_Holofoil.csv',
 'test_prices/ex4-1_Holofoil.csv',
 'test_prices/base6-2_Reverse_Holofoil.csv',
 'test_prices/col1-2_Holofoil.csv',
 'test_prices/xy3-5_Holofoil.csv',
 'test_prices/base1-11_Holofoil.csv',
 'test_prices/g1-2_Holofoil.csv',
 'test_prices/base1-13_Holofoil.csv',
 'test_prices/dp1-2_Holofoil.csv',
 'test_prices/basep-9_Holofoil.csv',
 'test_prices/base4-11_Holofoil.csv',
 'test_prices/base1-12_Holofoil.csv',
 'test_prices/sm9-14_Reverse_Holofoil.csv',
 'test_prices/base4-9_Holofoil.csv',
 'test_prices/bw11-3_Reverse_Holofoil.csv',
 'test_prices/pl1-5_Holofoil.csv',
 'test_prices/pl1-3_Holofoil.csv',
 'test_prices/xy2-

In [8]:
def calculate_mean_return(path):
    df = pd.read_csv(path)
    df['log_return'] = np.log(df['price'] / df['price'].shift(1))
    return np.mean(df["log_return"])

In [9]:
def calculate_matrice_rendement_avg(csv_paths):
    """
    Calcule la matrice des rendements moyens pour une liste de fichiers CSV
    avec leurs identifiants
    
    Args:
        csv_paths (list): Liste des chemins vers les fichiers CSV
        
    Returns:
        dict: Dictionnaire avec les IDs comme clés et les rendements moyens comme valeurs
    """
    import pandas as pd
    import numpy as np
    
    returns_dict = {}
    
    for path in csv_paths:
        try:
            # Lecture du CSV
            df = pd.read_csv(path)
            
            # On suppose que la colonne prix s'appelle 'Close' ou 'Price'
            price_column = 'Close' if 'Close' in df.columns else 'price'
            
            # Calcul des rendements logarithmiques
            returns = np.log(df[price_column] / df[price_column].shift(1)).dropna()
            
            # Calcul du rendement moyen
            mean_return = returns.mean()
            
            # Extraction de l'ID de la carte du nom du fichier
            card_id = path.split('/')[-1].replace('.csv', '')
            
            returns_dict[card_id] = mean_return
            
        except Exception as e:
            print(f"Erreur lors de la lecture de {path}: {str(e)}")
    
    return returns_dict


In [10]:
mu=calculate_matrice_rendement_avg(path)

In [11]:
mu

{'basep-10_Holofoil': -9.660028768184572e-18,
 'hgss1-13_Holofoil': -0.004003388091851543,
 'ex3-1_Holofoil': 0.0013957333335516855,
 'ex5-7_Holofoil': 0.0065693023892467745,
 'bw5-2_Reverse_Holofoil': -0.006231808208336775,
 'ex7-4_Reverse_Holofoil': -0.002880988859877866,
 'smp-SM04_Holofoil': 1.4966241753525395e-18,
 'col1-3_Holofoil': 0.0016357001737039405,
 'pop7-4_Normal': 0.0027570306470315244,
 'base4-12_Holofoil': -0.004078915617439009,
 'ex4-1_Holofoil': -6.530723674265627e-18,
 'base6-2_Reverse_Holofoil': 0.0026913715053542846,
 'col1-2_Holofoil': -0.0045896592518902025,
 'xy3-5_Holofoil': 0.009450116917050527,
 'base1-11_Holofoil': 0.0032188049498631,
 'g1-2_Holofoil': 0.0028894680739801042,
 'base1-13_Holofoil': 1.0884539457109378e-18,
 'dp1-2_Holofoil': -0.00047141905008265357,
 'basep-9_Holofoil': 0.0023756767857448895,
 'base4-11_Holofoil': -0.0014888789334149702,
 'base1-12_Holofoil': -1.0884539457109378e-18,
 'sm9-14_Reverse_Holofoil': 0.00024408418679544255,
 'base4-

In [12]:
returns_matrix = np.array([*mu.values()])

In [13]:
returns_matrix

array([-9.66002877e-18, -4.00338809e-03,  1.39573333e-03,  6.56930239e-03,
       -6.23180821e-03, -2.88098886e-03,  1.49662418e-18,  1.63570017e-03,
        2.75703065e-03, -4.07891562e-03, -6.53072367e-18,  2.69137151e-03,
       -4.58965925e-03,  9.45011692e-03,  3.21880495e-03,  2.88946807e-03,
        1.08845395e-18, -4.71419050e-04,  2.37567679e-03, -1.48887893e-03,
       -1.08845395e-18,  2.44084187e-04, -3.98417186e-03, -6.85445338e-03,
       -4.45774977e-03,  2.65310649e-18, -4.97689259e-03])

In [14]:
def get_last_prices(csv_paths):
    """
    Récupère le dernier prix pour chaque fichier CSV
    
    Args:
        csv_paths (list): Liste des chemins vers les fichiers CSV
        
    Returns:
        dict: Dictionnaire avec le nom du fichier comme clé et le dernier prix comme valeur
    """
    import pandas as pd
    
    last_prices = {}
    
    for path in csv_paths:
        try:
            # Lecture du CSV
            df = pd.read_csv(path)
            
            # On suppose que la colonne prix s'appelle 'Close' ou 'Price'
            price_column = 'Close' if 'Close' in df.columns else 'price'
            
            # Récupération du dernier prix
            last_price = df[price_column].iloc[-1]
            
            # Extraction du nom du fichier du chemin
            file_name = path.split('/')[-1].replace('.csv', '')
            
            last_prices[file_name] = last_price
            
        except Exception as e:
            print(f"Erreur lors de la lecture de {path}: {str(e)}")
            
    return last_prices


In [15]:
prices=get_last_prices(path)

In [16]:
prices

{'basep-10_Holofoil': 13.81,
 'hgss1-13_Holofoil': 5.96,
 'ex3-1_Holofoil': 40.17,
 'ex5-7_Holofoil': 9.73,
 'bw5-2_Reverse_Holofoil': 11.52,
 'ex7-4_Reverse_Holofoil': 38.92,
 'smp-SM04_Holofoil': 5.68,
 'col1-3_Holofoil': 11.12,
 'pop7-4_Normal': 7.09,
 'base4-12_Holofoil': 19.46,
 'ex4-1_Holofoil': 8.79,
 'base6-2_Reverse_Holofoil': 195.0,
 'col1-2_Holofoil': 9.1,
 'xy3-5_Holofoil': 8.08,
 'base1-11_Holofoil': 27.28,
 'g1-2_Holofoil': 8.32,
 'base1-13_Holofoil': 18.03,
 'dp1-2_Holofoil': 8.63,
 'basep-9_Holofoil': 40.05,
 'base4-11_Holofoil': 18.38,
 'base1-12_Holofoil': 21.67,
 'sm9-14_Reverse_Holofoil': 9.7,
 'base4-9_Holofoil': 9.72,
 'bw11-3_Reverse_Holofoil': 10.18,
 'pl1-5_Holofoil': 7.6,
 'pl1-3_Holofoil': 8.46,
 'xy2-12_Holofoil': 8.41}

In [17]:
finished_prices = np.array([*prices.values()])

In [18]:
finished_prices

array([ 13.81,   5.96,  40.17,   9.73,  11.52,  38.92,   5.68,  11.12,
         7.09,  19.46,   8.79, 195.  ,   9.1 ,   8.08,  27.28,   8.32,
        18.03,   8.63,  40.05,  18.38,  21.67,   9.7 ,   9.72,  10.18,
         7.6 ,   8.46,   8.41])

In [19]:
def calculate_weekly_prices_dict(folder_path):
    """
    Calcule les prix moyens hebdomadaires pour chaque carte
    
    Args:
        folder_path (str): Chemin vers le dossier contenant les fichiers CSV
        
    Returns:
        dict: Dictionnaire avec les IDs des cartes comme clés et leurs prix hebdomadaires comme valeurs
    """
    import os
    import pandas as pd
    
    weekly_prices = {}
    
    for file in os.listdir(folder_path):
        if file.endswith('.csv'):
            try:
                # Lecture du fichier CSV
                df = pd.read_csv(os.path.join(folder_path, file))
                
                # Conversion des colonnes de dates
                df['start_date'] = pd.to_datetime(df['start_date'])
                df['end_date'] = pd.to_datetime(df['end_date'])
                
                # Extraction des prix hebdomadaires
                prices = df['price'].tolist()
                
                # Extraction de l'ID de la carte du nom du fichier
                card_id = file.replace('.csv', '')
                
                # Stockage des prix dans le dictionnaire
                weekly_prices[card_id] = prices
                
            except Exception as e:
                print(f"Erreur lors du traitement de {file}: {e}")
    
    return weekly_prices


In [20]:
dataframe_weeks=calculate_weekly_prices_dict('test_prices')

In [21]:
dataframe_weeks

{'basep-10_Holofoil': [13.81,
  10.97,
  11.06,
  11.07,
  11.09,
  10.97,
  11.05,
  11.05,
  10.86,
  10.77,
  10.75,
  10.78,
  10.8,
  10.73,
  10.69,
  10.86,
  10.86,
  10.94,
  11.54,
  12.41,
  12.41,
  12.37,
  12.14,
  12.14,
  12.15,
  12.37,
  12.34,
  12.29,
  12.41,
  12.66,
  12.41,
  12.1,
  11.94,
  12.06,
  12.15,
  12.46,
  12.58,
  12.59,
  12.48,
  12.24,
  12.19,
  12.43,
  12.59,
  13.29,
  13.2,
  13.01,
  13.09,
  13.09,
  13.24,
  13.18,
  13.25,
  13.81],
 'hgss1-13_Holofoil': [7.31,
  7.03,
  7.03,
  6.94,
  6.94,
  6.92,
  6.92,
  6.92,
  6.88,
  6.77,
  6.77,
  6.74,
  6.49,
  6.38,
  6.38,
  6.38,
  6.62,
  6.62,
  6.24,
  6.24,
  6.24,
  6.24,
  6.44,
  6.44,
  6.44,
  6.44,
  6.44,
  6.33,
  6.43,
  6.8,
  6.8,
  6.61,
  6.65,
  6.63,
  6.63,
  6.7,
  6.48,
  6.48,
  6.48,
  6.53,
  6.53,
  6.5,
  6.24,
  6.1,
  6.24,
  6.24,
  6.24,
  6.24,
  6.04,
  6.04,
  6.04,
  5.96],
 'ex3-1_Holofoil': [37.41,
  37.41,
  35.05,
  35.05,
  35.05,
  35.05,
  35.05,

In [22]:
import pandas as pd

def calculer_matrice_covariance_pandas(donnees):
    """
    Calcule la matrice de covariance à partir d'un dictionnaire de données.

    Paramètres:
        donnees (dict): Un dictionnaire où les clés sont des identifiants et les valeurs sont des listes ou des tableaux numpy de prix.

    Retourne:
        pandas.DataFrame: La matrice de covariance.
    """
    # Convertir le dictionnaire en DataFrame
    df = pd.DataFrame(donnees)
    
    # Calculer la matrice de covariance
    return df.cov()



In [23]:
cov=calculer_matrice_covariance_pandas(dataframe_weeks)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [24]:
np.array(cov)

array([[ 8.23421719e-01, -1.42120965e-01,  1.48366652e+00,
         5.13080543e-01, -1.16250392e+00, -1.71892941e+00,
        -2.28788839e-02,  5.54020814e-01,  1.59142383e-01,
        -1.08448839e+00, -1.09139970e-01,  6.56824811e+00,
        -1.73787934e-01,  7.67312217e-01,  1.24132368e+00,
         5.46291704e-01,  4.50111011e-01,  8.54710407e-02,
         5.88271493e-02,  9.55651584e-02,  1.42714268e+00,
        -2.10389140e-02,  8.45295777e-01, -4.87959879e-01,
        -1.47198190e-01, -3.11187934e-01, -5.28283560e-01],
       [-1.42120965e-01,  8.95357466e-02, -2.83045701e-01,
        -1.77352338e-01,  3.03174510e-01,  3.86884314e-01,
        -1.66743590e-02, -7.86069382e-02, -9.53285068e-02,
         3.23954299e-01,  4.42538462e-02, -2.24036244e+00,
         1.38332579e-01, -2.27225641e-01, -3.44058220e-01,
        -1.72413575e-01, -3.75057919e-01,  3.35743590e-02,
        -2.75099246e-01,  1.40454751e-01, -3.75813575e-01,
         1.76404223e-02, -8.63423831e-02,  2.73880090e-

In [31]:
budget=100
num_cards_wanted=10
optimizer = MarkowitzPortfolioOptimizer(
    returns=returns_matrix,
    prices=finished_prices,
    cov_matrix=np.array(cov),
    budget=budget,
    num_cards=num_cards_wanted
)

In [32]:
weights, invested_amount = optimizer.optimize()
selected_cards = np.where(weights > 0)[0]

print("Cartes sélectionnées :", selected_cards)
print("Montant total investi : {:.2f}".format(invested_amount))


Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/nayelbenabdesadok/opt/anaconda3/envs/pokemon_card/lib/python3.9/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/sg/lshv0q7145ggm8z9kc3b1y4r0000gn/T/334eafb37a1741e3a925866b110ad6da-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/sg/lshv0q7145ggm8z9kc3b1y4r0000gn/T/334eafb37a1741e3a925866b110ad6da-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 171 RHS
At line 175 BOUNDS
At line 203 ENDATA
Problem MODEL has 3 rows, 27 columns and 81 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is -0.0275815 - 0.00 seconds
Cgl0004I processed model has 2 rows, 26 columns (26 integer (26 of which binary)) and 52 elements
Cbc0038I Initial state - 2 integers unsatisfied sum - 0.68778
Cbc0038I Solution found of -0.0267645
Cbc0038I Before mini branch 